### ISSUE TITLE
你的工程有错误吧

### ISSUE THREAD

**Issue by chen1026241686** [wangjiegulu/ImageLoaderSample#1]
我下载了之后导入到eclipse右错误，并且你的lib里面的那个jar包的代码，跟你的工程的代码一样的啊，那个包没有用啊

**Comment by wangjiegulu** [comment]
ImageLoaderSample需要依赖另外一个项目：https://github.com/wangjiegulu/AndroidBucket
使用时请同时引用这两个项目，ImageLoaderSample/library中的jar文件（ImageLoaderSample.jar不要使用）

在 2014年5月19日 上午10:21，chen1026241686 notifications@github.com写道：
